categories:
  entertainment:
    description: Subscriptions, shows, movies, events
    display_name: Entertainment
    synonyms:
    - value: netflix
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539749'
      meta: {}
    - value: spotify
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539792'
      meta: {}
    - value: bookmyshow
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539802'
      meta: {}
    - value: zee5
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539807'
      meta: {}
    - value: hotstar
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539812'
      meta: {}
    - value: kanav
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539816'
      meta: {}
    - value: shaurya
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539820'
      meta: {}
    - value: vaip
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539824'
      meta: {}
  groceries:
    description: Supermarkets and grocery stores
    display_name: Groceries
    synonyms:
    - value: big bazaar
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539849'
      meta: {}
    - value: dmart
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539853'
      meta: {}
    - value: reliance fresh
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539857'
      meta: {}
    - value: more supermarket
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539861'
      meta: {}
    - value: spencers
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539865'
      meta: {}
  restaurants:
    description: Restaurants and food delivery
    display_name: Restaurants
    synonyms:
    - value: mcdonalds
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539870'
      meta: {}
    - value: swiggy
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539874'
      meta: {}
    - value: zomato
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539878'
      meta: {}
    - value: dominos
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539881'
      meta: {}
    - value: kfc
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539892'
      meta: {}
    - value: vendikin
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539896'
      meta: {}
    - value: ka
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539900'
      meta: {}
  shopping:
    description: Online and offline retail
    display_name: Shopping
    synonyms:
    - value: amazon
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539904'
      meta: {}
    - value: flipkart
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539908'
      meta: {}
    - value: myntra
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539912'
      meta: {}
    - value: ajio
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539916'
      meta: {}
    - value: nykaa
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539920'
      meta: {}
    - value: flushkaran
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539923'
      meta: {}
    - value: karan
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539927'
      meta: {}
    - value: kan
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539930'
      meta: {}
    - value: kap
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539934'
      meta: {}
    - value: ash
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539939'
      meta: {}
  travel:
    description: Transport, flights, trains, taxis
    display_name: Travel
    synonyms:
    - value: ola
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539946'
      meta: {}
    - value: uber
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539952'
      meta: {}
    - value: irctc
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539957'
      meta: {}
    - value: indigo
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539963'
      meta: {}
    - value: goibibo
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539968'
      meta: {}
    - value: kp
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539973'
      meta: {}
  utilities:
    description: Bills and utilities
    display_name: Utilities
    synonyms:
    - value: bescom
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539982'
      meta: {}
    - value: airtel broadband
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539987'
      meta: {}
    - value: tata power
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539992'
      meta: {}
    - value: bwssb
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.539997'
      meta: {}
    - value: vodafone
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.540002'
      meta: {}
    - value: jassi
      source: seed
      weight: 0.8
      created_at: '2025-11-21T18:40:07.540010'
      meta: {}
updated_at: '2025-11-12T18:15:20.493787'
updated_by: streamlit-admin
version: 14
