categories:
  entertainment:
    description: Subscriptions, shows, movies, events
    display_name: Entertainment
    synonyms:
    - netflix
    - spotify
    - bookmyshow
    - zee5
    - hotstar
  groceries:
    description: Supermarkets and grocery stores
    display_name: Groceries
    synonyms:
    - big bazaar
    - dmart
    - reliance fresh
    - more supermarket
    - spencers
  restaurants:
    description: Restaurants and food delivery
    display_name: Restaurants
    synonyms:
    - mcdonalds
    - swiggy
    - zomato
    - dominos
    - kfc
    - vendikin
  shopping:
    description: Online and offline retail
    display_name: Shopping
    synonyms:
    - amazon
    - flipkart
    - myntra
    - ajio
    - nykaa
  travel:
    description: Transport, flights, trains, taxis
    display_name: Travel
    synonyms:
    - ola
    - uber
    - irctc
    - indigo
    - goibibo
    - kp
  utilities:
    description: Bills and utilities
    display_name: Utilities
    synonyms:
    - bescom
    - airtel broadband
    - tata power
    - bwssb
    - vodafone
updated_at: '2025-11-08T18:41:43.211359'
updated_by: streamlit-admin
version: 4
